src/Form/CalendarType.php
<?php

namespace App\Form;

use App\Entity\Event;
use App\Repository\CategoryRepository;
use App\Repository\EntityRepository;
use App\Repository\UserRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;

class CalendarType extends AbstractType
{
    private $translator;
    private $usersChoices;
    private $categoryChoices;
    private $entityChoices;

    public function __construct(
        TranslatorInterface $translator,
        UserRepository $userRepository,
        CategoryRepository $categoryRepository,
        EntityRepository $entityRepository
    ) {
        $this->translator = $translator;
        $this->usersChoices = $userRepository->getActiveUsersChoices();
        $this->categoryChoices = $categoryRepository->getActiveCategoriesChoices();
        $this->entityChoices = $entityRepository->getActiveEntitiesChoices();

    }

    public function getName()
    {
        return self::class;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('category', ChoiceType::class, [
                'label' => false,
                'placeholder' => $this->translator->trans('label.category') . '...',
                'choices' => array_flip($this->categoryChoices),
                'attr' => [
                    'class' => 'form-control select2-single',
                ]
            ])
            ->add('entity', ChoiceType::class, [
                    'required' => false,
                    'label' => false,
                    'placeholder' =>  $this->translator->trans('label.entity') . '...',
                    'choices' => array_flip($this->entityChoices),
                    'attr' => [
                        'class' => 'form-control select2-single',
                    ]
                ]
            )
            ->add('status', ChoiceType::class, [
                    'required' => false,
                    'label' => false,
                    'placeholder' =>  $this->translator->trans('label.status') . '...',
                    'choices' => array_flip(Event::STATUS),
                    'attr' => [
                        'class' => 'form-control select2-single',
                    ]
                ]
            )
            ->add('accepted', ChoiceType::class, [
                    'required' => false,
                    'label' => false,
                    'placeholder' =>  $this->translator->trans('label.is_accepted') . '...',
                    'choices' => array_flip(Event::ACCEPTED),
                    'attr' => [
                        'class' => 'form-control',
                    ]
                ]
            );
        if ($options['hideAddedBy'] === false) {
            $builder
                ->add('addedBy', ChoiceType::class, [
                    'label' => false,
                    'placeholder' => $this->translator->trans('label.added_by') . '...',
                    'choices' => array_flip($this->usersChoices),
                    'attr' => [
                        'class' => 'form-control select2-single',
                    ]
                ]);
        }


    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => null,
            'hideAddedBy' => false
        ]);
    }
}

templates/common/calendar/modals/eventDetailsContent.html.twig
{{ form_start(form, { 'attr': {'class': 'form-horizontal'} }) }}
<div class="form-group">
    <label class="col-lg-2 control-label">{{ 'label.acceptance'|trans() }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            <div class="form-control-static">
                {% include 'common/events/acceptanceTemplate.html.twig' with {'isAccepted': event.isAccepted } %}
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.imageFile) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            {{ form_widget(form.imageFile) }}
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.name) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            {{ form_widget(form.name) }}
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.startAt) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            {{ form_widget(form.startAt) }}
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.endAt) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            {{ form_widget(form.endAt) }}
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.description) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            {{ form_widget(form.description, { 'attr': {'class': 'form-control summernote-no-toolbar'} }) }}
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.agenda) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            {{ form_widget(form.agenda, { 'attr': {'class': 'form-control summernote-no-toolbar'} }) }}
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.entity) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            {{ form_widget(form.entity) }}
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.category) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            {{ form_widget(form.category) }}
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.city) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            {{ form_widget(form.city) }}
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.address) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            {{ form_widget(form.address) }}
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.externalLink) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            {{ form_widget(form.externalLink) }}
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.tickets) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            {{ form_widget(form.tickets, { 'attr': {'class': 'form-control summernote-no-toolbar'} }) }}
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-2 control-label">{{ form_label(form.freeEntry) }}</label>
    <div class="col-lg-10">
        <div class="bs-component">
            <label class="switch block mt5 switch-primary">
                {{ form_widget(form.freeEntry) }}
                {% if form_errors(form.freeEntry) is not empty %}
                    <div class="error-form">{{ form_errors(form.freeEntry) }}</div>
                {% endif %}
                <label for="event_preview_freeEntry" data-on="{{ 'label.yes'|trans() }}" data-off="{{ 'label.no'|trans() }}"></label>
            </label>
        </div>
    </div>
</div>

{{ form_end(form) }}

templates/common/calendar/modals/modalTemplate.html.twig
<div class="admin-form theme-primary popup-basic popup-lg mfp-with-anim mfp-hide" id="calendarEventDetails"  role="dialog" >
    <div class="panel">
        <div class="panel-heading">
        <span class="panel-title">
          <i class="fa fa-calendar-check"></i>{{ 'header.event_details'|trans() }}
        </span>
        </div>
        <div class="panel-body p25">
            <div class="section row event-detail-loader">
                <div class="loader"></div>
            </div>
            <div class="section row event-detail-content">
            </div>
        </div>
        <div class="panel-footer  text-right">
            <span class="button btn-default close-modal">{{ 'action.back'|trans() }}</span>
            <a id="edit-event-action" style="display: none;"><span class="button btn-success" >{{ 'action.edit'|trans() }}</span></a>
        </div>
    </div>
</div>